SECRET_KEY : "157a6ca4d2e34d77a949d61f8724d8e878e51e66b2babe2adc"
PERMANENT_SESSION_LIFETIME : 50
MYSQL_HOST : "localhost"
MYSQL_USER : "root"
MYSQL_PASSWORD : ""
MYSQL_DB : "codon.io"
MYSQL_CURSORCLASS : "DictCursor"
MAIL_SERVER: "smtp.gmail.com"
MAIL_PORT: 465
MAIL_USERNAME: "YourGmailAccount"
MAIL_PASSWORD: "YourPassword"
MAIL_USE_TLS: False
MAIL_USE_SSL: False
MAIL_DEFAULT_SENDER: "help@codon.io"
